version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: q1w2e3
      POSTGRES_DB: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always